version: '2.1'
services:
  app:
    image: ruby:2.5.0
    working_dir: /usr/src/app
    command: bundle install
    volumes:
      - .:/usr/src/app
    environment:
      BUNDLE_PATH: /usr/src/app/.bundle
